version: '3.4'

services:
  docker:
    image: docker:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_docker$
    volumes:
      - C:\Users\EXO SMART PRO Q2\Documents\Visual Studio 2017\Backup Files\Docker\Docker:C:\app
      - C:\Users\EXO SMART PRO Q2\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_docker$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_docker$ bin\\Debug\\netcoreapp2.1\\Docker.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
